name: Check Commits

on: 
  pull_request:

jobs:
  check-commits:
    permissions:
      contents: read
      checks: write
    uses: FlowingCode/GithubActions/.github/workflows/check-commits.yml@feature/wip-action-required
